source 'https://github.com/SDOSLabs/cocoapods-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
	pod 'SDOSFirebase', :path => '../../'
end

target :SDOSFirebaseSample do
	shared_pods
end
